
[dependencies]
  fastly = "^0.8.0"
  woothee = "0.13.0"

[package]
  authors = []
  edition = "2018"
  name = "rust-demo"
  publish = false
  version = "0.1.0"

[profile]

  [profile.release]
    debug = 1
