# The default local configuration
[local_server]
	[local_server.backends]
		[local_server.backends.backend_a]
			url = "http://worldtimeapi.org/api/timezone/America/Los_Angeles"
	[local_server.dictionaries]
		[local_server.dictionaries.values]
			file = "values.json"
			format = "json"
		[local_server.dictionaries.strings]
			format = "inline-toml"
		[local_server.dictionaries.strings.contents]
			"en.welcome" = "welcome"
			"de.welcome" = "willkommen"
			"fr.welcome" = "bienvenue"
			"es.welcome" = "bienvenido"