# An alternate config. To use, start service with `make serve FASTLY_CONFIG=alt`
[local_server]
	[local_server.backends]
		[local_server.backends.backend_a]
			url = "http://localhost:4000"
	[local_server.dictionaries]
		[local_server.dictionaries.values]
			file = "values.json"
			format = "json"
		[local_server.dictionaries.strings]
			format = "inline-toml"
		[local_server.dictionaries.strings.contents]
			"en.welcome" = "s'up"
			"de.welcome" = "hallo"
			"fr.welcome" = "bonjour"
			"es.welcome" = "hola"